version: "3"

services:
    rabbitmq:
        image: "rabbitmq:management-alpine"
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        # environment:
        #     - RABBITMQ_DEFAULT_USER=gideon
        #     - RABBITMQ_DEFAULT_PASS=password
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/home/gideon/Documents/personal/rabbitmqdocker/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/home/gideon/Documents/personal/rabbitmqdocker/var/log/rabbitmq
        networks:
            - rabbitmq_go_net

networks:
    rabbitmq_go_net:
        driver: bridge
